### ISSUE TITLE
html5 support

### ISSUE THREAD

**Issue by ctalkington** [wpsitecare/foxtrot#9]
generally, its recommended to define what you want to opt-in for as far as html5 goes such:

```php
add_theme_support( 'html5', array(
    'search-form',
    'comment-form',
    'comment-list'
  ));
```

Core even has a check for this:

https://github.com/aaronjorbin/develop.wordpress/blob/master/src/wp-includes/theme.php#L1544

**Comment by robneu** [comment]
Interesting. I must have missed that somewhere along the way. I'll get that patched. Thanks man!
